clip_range: 0.2
computed_batch_size: 4096
computed_total_rollout: 16384
device: cpu
disable_dynamic: true
ent_coef: 0.001
eval_episodes: 5
eval_every_steps: 100000
eval_use_train_options: true
gae_lambda: 0.95
gamma: 0.995
gui: false
leader_speed_scale: 0.3
learning_rate: 0.0003
load: runs/ppo_multi/20251130_145955_stage0_warm/checkpoints/best_model.zip
load_latest: true
load_vecnorm: runs/ppo_multi/20251130_145955_stage0_warm/vecnormalize_final.pkl
log_dir: runs/ppo_multi/20251130_151002_stage1_easy
max_grad_norm: 0.5
n_envs: 8
n_epochs: 10
n_steps: 2048
passthrough:
  alt_w: 0.4
  form_var_gain: 0.3
  form_w_max: 0.4
  form_w_mean: 2.0
  formation_spacing: 0.85
  huber_delta: 0.4
  min_sep: 0.55
  sep_gain: 1.5
policy_net_arch:
- 256
- 256
progress_log_every: 10000
save_every_steps: 200000
seed: 0
spawn_in_formation: true
start_method: forkserver
target_kl: 0.03
total_timesteps: 3000000
vf_coef: 1.0
